general:
  # Enable the auto start and stop of games
  autostart: true
  # Minimum number of players to auto start the game
  autostartMin: 7
  # Auto stop the game when the players fall to this level
  autostopMin: 5